plugins {
    id 'com.android.library'
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
}

rootProject.domain.plugins.each {
    apply plugin: it
}

rootProject.presentation.plugins.each {
    apply plugin: it
}

android {
    namespace 'com.zarinfanavaran.presentation'
    compileSdk versions.compileSdk

    defaultConfig {
        minSdk versions.minSdk
        targetSdk versions.compileSdk
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility versions.JavaVersion
        targetCompatibility versions.JavaVersion
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        dataBinding = true
    }
}

dependencies {
    rootProject.presentation.libs.each {
        add(it.configuration, it.dependency, it.options)
    }

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
kapt {
    correctErrorTypes true
}