plugins {
    id 'com.android.library'
}

rootProject.domain.plugins.each {
    apply plugin: it
}

android {
    namespace 'com.zarinfanavaran.domain'
    compileSdk versions.compileSdk

    defaultConfig {
        minSdk versions.minSdk
        targetSdk versions.compileSdk
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        buildConfigField 'String', 'BASE_URL', fields.BaseUrl
        buildConfigField 'String', 'DEV_URL', fields.DevUrl
        buildConfigField 'String', 'SHARE_URL', fields.ShareUrl
        buildConfigField 'String', 'MEDIA_URL', fields.MediaUrl
        buildConfigField 'String', 'AUTHORIZATION', fields.Authorization
        buildConfigField 'String', 'TOKEN_PREFIX', fields.TokenPrefix
        buildConfigField 'String', 'DEFAULT_TOKEN', fields.DefaultToken
        buildConfigField 'String', 'SESSION_LOGIN', fields.SessionLogin
        buildConfigField 'String', 'SESSION_TOKEN', fields.SessionToken
        buildConfigField 'String', 'REGISTER_TOKEN', fields.RegisterToken
        buildConfigField 'String', 'DEFAULT_LANGUAGE', fields.DefaultLanguage
        buildConfigField 'String', 'SESSION_LANGUAGE', fields.SessionLanguage
        buildConfigField 'String', 'DEFAULT_THEME', fields.DefaultTheme
        buildConfigField 'String', 'SESSION_THEME', fields.SessionTheme
        buildConfigField 'String', 'USER', fields.User
        buildConfigField 'String', 'APP_NAME', fields.AppName
        buildConfigField 'String', 'DATABASE_NAME', fields.DatabaseName
        buildConfigField 'String', 'APP_VERSION', fields.AppVersion
        buildConfigField 'String', 'USER_AGENT', fields.UserAgent
        buildConfigField 'String', 'SESSION_PUSH_TOKEN', fields.SessionPushToken
        buildConfigField 'String', 'ENVIRONMENT', fields.Environment
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility versions.JavaVersion
        targetCompatibility versions.JavaVersion
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        dataBinding = true
    }
}

dependencies {

    rootProject.domain.libs.each {
        add(it.configuration, it.dependency, it.options)
    }

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
kapt {
    correctErrorTypes true
}