plugins {
    id 'com.android.application'
}

rootProject.domain.plugins.each {
    apply plugin: it
}

rootProject.app.plugins.each {
    apply plugin: it
}

android {
    namespace 'com.zarinfanavaran.shop'
    compileSdk versions.compileSdk

    defaultConfig {
        applicationId "com.zarinfanavaran.shop"
        minSdk versions.minSdk
        targetSdk versions.compileSdk
        versionCode versions.appVersion
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility versions.JavaVersion
        targetCompatibility versions.JavaVersion
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        dataBinding = true
    }
}

dependencies {

    rootProject.app.libs.each {
        add(it.configuration, it.dependency, it.options)
    }

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}